operation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spy.urls', namespace="trail")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spy/urls.py
from django.urls import path

from spy.views import CodeView, ClueView, StartView, BriefView, FinishView

app_name = "spy"

urlpatterns = [
    path('', StartView.as_view(), name="start"),
    path('brief/', BriefView.as_view(), name="brief"),
    path('finish/', FinishView.as_view(), name="finish"),
    path('<int:clue>/', ClueView.as_view(), name="clue"),
    path('code/', CodeView.as_view(), name="code"),
]

spy/models.py
from django.db import models


# Create your models here.
class TrailStep(models.Model):
    sequence = models.IntegerField(unique=True)
    directions = models.TextField()
    clue = models.TextField()
    image = models.BooleanField(default=False)
    answer = models.CharField(max_length=20)
    hint = models.TextField(blank=True)

    class Meta:
        ordering = ['sequence']

spy/forms.py
from django import forms

from spy.models import TrailStep


class AnswerForm(forms.ModelForm):
    class Meta:
        model = TrailStep
        fields = ['answer']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['answer'].label = ""
        self.fields['answer'].widget.attrs['placeholder'] = "Answer"
        self.fields['answer'].widget.attrs['autocomplete'] = 'off'

spy/views.py
# Create your views here.
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

from spy.forms import AnswerForm
from spy.models import TrailStep


class StartView(TemplateView):
    template_name = 'start.html'

    def dispatch(self, request, *args, **kwargs):
        if "restart" in request.GET.keys():
            request.session.clear()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session.get("current_clue"):
            context['re'] = "Restart"
            context['current'] = self.request.session.get("current_clue")
        return context


class ClueView(FormView):
    template_name = 'clue.html'
    form_class = AnswerForm

    clue = None

    def dispatch(self, request, *args, **kwargs):
        self.clue = get_object_or_404(TrailStep, pk=kwargs.get('clue'))
        if "restart" in request.GET.keys():
            request.session.clear()
        request.session["current_clue"] = self.clue.sequence

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for f in ['directions', 'clue', 'image', 'sequence', 'hint']:
            context[f] = getattr(self.clue, f, None)
        if context['image']:
            context['image_path'] = f"images/clue{context['sequence']}.png"
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial['answer'] = self.request.session.get(f"clue_{self.clue.sequence}")
        return initial

    def form_valid(self, form):
        self.request.session[f"clue_{self.clue.sequence}"] = form.cleaned_data.get('answer').upper()
        return super().form_valid(form)

    def get_success_url(self):
        sequence = self.clue.sequence
        try:
            next = TrailStep.objects.get(sequence=sequence + 1)
            url = reverse_lazy("spy:clue", kwargs={'clue': next.sequence})
        except:
            url = reverse_lazy("spy:code")
        return url


class CodeView(TemplateView):
    template_name = 'code.html'

    class Result(object):
        def __init__(self, clue, user_answer=None, correct=None):
            self.clue = clue
            self.user_answer = user_answer
            self.correct = correct

        @property
        def colour(self):
            if self.correct:
                return "success"
            if self.correct == None:
                return "light"
            return "danger"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_results(self):
        clues = TrailStep.objects.all()
        results = []
        total_correct = 0
        for clue in clues:
            user_answer = self.request.session.get(f"clue_{clue.sequence}", "").upper()
            correct = None
            if user_answer:
                if user_answer == clue.answer.upper():
                    correct = True
                    total_correct += 1
                else:
                    correct = False
            results.append(self.Result(clue.sequence, user_answer, correct))
        return results, total_correct, clues

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        results, total_correct, clues = self.get_results()
        context['results'] = results
        if any([
            total_correct == clues.count(),
            settings.DEBUG
        ]):
            context['finished'] = True
        return context


class FinishView(CodeView):
    template_name = 'finish.html'

    def dispatch(self, request, *args, **kwargs):
        results, total_correct, clues = self.get_results()
        if total_correct != clues.count():
            if not settings.DEBUG:
                return HttpResponseRedirect(reverse_lazy("spy:code"))
        return super().dispatch(request, *args, **kwargs)


class BriefView(CodeView):
    template_name = 'brief.html'

spy/templates/brief.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block content %}
    <h2>Mission Briefing</h2>
    <p>Calling all spies and wannabe secret agents! We need your help to find the secret code hidden in and around Goole
        to prevent the demolition of our beloved water towers by an underground organised crime group.</p>

    <p>The walk covers roughly 3.5 miles and is suitable for pushchairs. Expect it to take 1.5 – 2 hours, depending on how
        well you know Goole! It is mainly set on flat footpaths so normal walking shoes are fine. It is also dog
        friendly, although smaller dogs may appreciate being carried over the foot bridge on the docks rather than
        walking across the metal grid!</p>

    <p>Free parking is available at East Riding Leisure in Goole, adjacent to the Jobcentre Plus. The address is North
        Street, Goole, East Yorkshire, United Kingdom, DN14 5QB.<a class="btn btn-success btn-small" target="_blank"
                                                                   href="https://www.google.com/maps/dir//53.7025035,-0.8692136/@53.7027737,-0.9041753,13z"><i
                class="fad fa-map-marker" aria-hidden="true"></i> Directions</a></p>
    <p>The code is 24 digits (letters & numbers) and the app will store your answers.</p>
    <p>Please add photos of your walk to the Facebook page for us all to enjoy.</p>


{% endblock %}
{% block footer %}
    <a class="btn btn-danger btn-large" href="{% url "spy:start" %}">Back to Start</a> &nbsp;
    <a href="https://fb.me/opsaltpepperpots" target="_blank" class="btn btn-primary btn-large"><i
            class="fab fa-facebook"></i> Follow us on Facebook</a>
{% endblock %}

spy/templates/clue.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block content %}
    <h2>Directions</h2>
    <p>{{ directions }}</p>
    <h2>Clue {{ sequence }}</h2>
    <p>{{ clue }}</p>
    {% if image %}
        <p><img class="img-thumbnail img-fluid" src="{% static image_path %}"/></p>
    {% endif %}
    {% if hint %}
        <a href="#" class="btn btn-warning hint-btn"><i class="fad fa-question"></i> Get a hint</a>
        <div class="hint d-none">
            <p>{{ hint }}</p>
        </div>
    {% endif %}

{% endblock %}
{% block footer %}
    <form action="{% url "spy:clue" sequence %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <a href="{% url "spy:code" %}" class="btn btn-secondary"><i class="fad fa-th"></i> Check Progress</a>

            <button type="submit" class="btn btn-primary"><i class="fad fa-forward"></i> Next Clue</button>
        {% endbuttons %}
    </form>
{% endblock %}

spy/templates/code.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Code Check</h1>
        <div class="row">
            {% for result in results %}
                <div class="col-2">
                    <a class="link-unstyled" href="{% url "spy:clue" result.clue %}">
                        <div class="card text-white bg-{{ result.colour }}">

                            <span class="code">
                                {% if result.user_answer %}
                                    {{ result.user_answer }}
                                {% else %}
                                    &nbsp;
                                {% endif %}
                            </span>

                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}
    <p>Select a clue to go to it or </p>
    <a class="btn btn-danger btn-large" href="{% url "spy:start" %}"><i class="fad fa-backward"></i> Back to Start</a> &nbsp;
    <a href="https://m.me/opsaltpepperpots" target="_blank" class="btn btn-primary btn-large"><i class="fab fa-facebook-messenger"></i> Take a screenshot, send it to us</a>
    {% if finished %}

    <a class="btn btn-success btn-large" href="{% url "spy:finish" %}"><i class="fad fa-trophy"></i>    Mission Complete</a> &nbsp;
    {% endif %}
{% endblock %}

spy/templates/finish.html
{% extends 'base.html' %}
{% load static %}
{% block header %}{% endblock %}
{% block content %}
    <div class="position-absolute top-0 start-0 behind"><img class="img-fluid" src="{% static 'images/ts.png' %}"/>
    </div>
    <h1 class="mb-1">Operation: Salt & Pepper Pots</h1>
    <p>Join North Street and walk away from the clock tower. After carefully crossing Aire Street, you should be able to
        see your starting point.</p>
    <p> Phew! Well done spies and don’t forget to submit your cracked code by private message to the chief operator for
        a mention on the page.</p>
    <p> We’d also love to see pics from your walk (No Spoilers!)</p>
{% endblock %}

{% block footer %}
    <a class="btn btn-danger btn-large" href="{% url "spy:code" %}"><i class="fad fa-th"></i> View The Code</a> &nbsp;
    <a href="https://m.me/opsaltpepperpots" target="_blank" class="btn btn-primary btn-large"><i
            class="fab fa-facebook-messenger"></i> Take a screenshot, send it to us</a>
    <a href="https://fb.me/opsaltpepperpots" target="_blank" class="btn btn-primary btn-large"><i
            class="fab fa-facebook"></i> Follow us on Facebook</a>
{% endblock %}

spy/templates/start.html
{% extends 'base.html' %}
{% load static %}
{% block header %}{% endblock %}
{% block content %}
    <div class="position-absolute top-0 start-0 behind"><img class="img-fluid" src="{% static 'images/ts.png' %}"/>
    </div>
    <h1 class="mb-1">Operation: Salt & Pepper Pots</h1>
    <p><a class="btn btn-info btn-large" href="{% url "spy:brief" %}"><i class="fad fa-user-secret"></i> Mission Briefing</a></p>
    {% if re %}
        <p><a class="btn btn-warning btn-large" href="{% url "spy:clue" 1 %}?restart"><i class="fad fa-forward"></i> Restart Mission</a></p>
        <p><a class="btn btn-success" href="{% url "spy:clue" current %}"><i class="fad fa-forward"></i> Continue Mission (Clue {{ current }})</a></p>
    {% else %}
        <p><a class="btn btn-success btn-large" href="{% url "spy:clue" 1 %}"><i class="fad fa-forward"></i> Start Mission</a></p>
    {% endif %}
    <p><a class="btn btn-secondary btn-small" target="_blank"
          href="https://www.google.com/maps/dir//53.7025035,-0.8692136/@53.7027737,-0.9041753,13z"><i
                class="fad fa-map-marker" aria-hidden="true"></i> Directions to
        start</a>
    </p>
    <p><a href="https://fb.me/opsaltpepperpots" target="_blank" class="btn btn-primary btn-large"><i
            class="fab fa-facebook"></i> Follow us on Facebook</a></p>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>{% block title %}{% endblock %}Operation: Salt & Pepper Pots</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oxygen+Mono&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5de507c650.js" crossorigin="anonymous"></script>
    <!-- Favicons -->
    {#<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">#}
    {#<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">#}
    {#<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">#}
    {#<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">#}
    {#<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">#}
    {#<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">#}
    <meta name="theme-color" content="#7952b3">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/site.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center">

<div class="cover-container d-flex w-100 h-100 p-1 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            {% block header %}<h3 class="mb-0">Operation: Salt & Pepper Pots</h3>{% endblock %}
        </div>

    </header>
    <main class="flex-shrink-0">
        {% block content %}
        {% endblock %}
        <div class="position-absolute bottom-0 end-0 behind"><img class="img-fluid"
                                                                  src="{% static 'images/clip.png' %}"/></div>
    </main>

    <footer class="footer mt-auto py-3 px-0">
        <div class="container">
            {% block footer %}
            {% endblock %}
        </div>
    </footer>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous"></script>
<script src="{% static "js/site.js"%}" crossorigin="anonymous"></script>
</body>
</html>